name: ci
on: [push]
jobs:
  regress:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Library build
        run: |
         rm -rf ~/.local/lib/python3.8/site-packages/openram*
         make library
      - name: Build conda
        run: |
         ./install_conda.sh
      - name: PDK Install
        run: |
         export OPENRAM_HOME="${{ github.workspace }}/compiler"
         export OPENRAM_TECH="${{ github.workspace }}/technology"
         #cd $OPENRAM_HOME/tests
         #export PDK_ROOT="${{ github.workspace }}/pdk"
         #make pdk
         #make install
      - name: Regress
        run: |
         export OPENRAM_HOME="${{ github.workspace }}/compiler"
         export OPENRAM_TECH="${{ github.workspace }}/technology"
         export FREEPDK45="/home/github-runner/FreePDK45"
         # KLAYOUT_PATH breaks klayout installation. Unset it for now...
         unset KLAYOUT_PATH
         #cd $OPENRAM_HOME/.. && make pdk && make install
         #export OPENRAM_TMP="${{ github.workspace }}/scn4me_subm_temp"
         #python3-coverage run -p $OPENRAM_HOME/tests/regress.py -j 12 -t scn4m_subm
         #$OPENRAM_HOME/tests/regress.py -j 24 -t scn4m_subm
         cd $OPENRAM_HOME/tests
         make clean
         make -k -j 48
      - name: Archive
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
         name: Regress Archives
         path: ${{ github.workspace }}/compiler/tests/results/*
